{
  "language": "cpp",
  "os": [
    "linux"
  ],
  "compiler": [
    "clang"
  ],
  "group": "stable",
  "dist": "xenial"
}


before-script:
  composer install --no-interaction
  
 script:
  - introduccion.cpp
