language: cpp
compiler: 
  -gcc
  -clang
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main"
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6
  - sudo apt-get install clang++-6.0
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: 
  - clang++ clase.cpp complejidad.cpp -o tarea
  - ./tarea -i fuente3.cpp
